### ISSUE TITLE
Book Pull Requests

### ISSUE THREAD

**Issue by raineorshine** [charleslbryant/hello-react-and-typescript#2]
Thanks for the book! It's helping quickly get started with react and typescript. There have been a couple steps at the beginning of the book where I got hung up, but I figured it out. Is there a place where I can submit a pull request to the book itself so that I can propose edits that might help future readers?

**Comment by raineorshine** [comment]
Never mind... found the comment feature!

**Comment by charleslbryant** [comment]
Thanks so much for your feedback. I never finished this book, but I'm glad you were able to get something from it.
